<a href="https://colab.research.google.com/github/cjayjonathan/285-Machine-Learning-Projects-with-Python/blob/main/Week02_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ar= np.array(5)

print(ar)
np.ndim(ar)


5


0

In [2]:
#Array creation
import numpy as np
a = np.array((1,2,3,4))
b = np.array([1,2,3,4])


In [3]:
a

array([1, 2, 3, 4])

In [4]:
b

array([1, 2, 3, 4])

In [5]:
#numpy.ones(shape, dtype=float, order='C')

import numpy as np
ar=np.zeros( (4,8), dtype=np.int16 )
print(ar)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [6]:
ar.dtype

dtype('int16')

In [7]:
import numpy as np
ar=np.empty( (2,3) )
print(ar)


[[2.47380915e-315 0.00000000e+000 1.54123330e+256]
 [1.94531707e+227 1.06098894e-153 8.19148733e+247]]


In [8]:
import numpy as np
ar=np.arange( 1,30,5)
print(ar)


[ 1  6 11 16 21 26]


In [9]:
import numpy as np
ar=np.array([[[ 1., 0., 0.,9], [ 0., 1., 2.,12], [ 1., 0., 0.,9]],
             [[ 1., 0., 0.,9], [ 0., 1., 2.,12],[ 1., 0., 0.,9]]])
print(np.shape(ar))


(2, 3, 4)


In [10]:
np.size(ar)

24

In [11]:
import numpy as np
ar=np.array([[ 1., 0., 0.],
       [ 0., 1., 2.]])
print(ar.dtype)


float64


In [12]:
ar

array([[1., 0., 0.],
       [0., 1., 2.]])

In [13]:
import numpy as np
b = np.arange(24).reshape(4,3,2)
#print(b)

In [14]:
np.ndim(b)

3

In [ ]:
ar=np.array([ 1., 4., 0.])
print(np.ndim(ar))

In [ ]:
#2d
#Array has 1-D arrays as its elements is called a 2-D array.
ar=np.array([[ 1.,4., 0.],
[ 3., 1., 2.],[ 3., 1., 2.]])
print(np.ndim(ar))


In [ ]:
#3d
#similar logic with 2d
#Array that has 2-D arrays (matrices) as its elements is called 3-D array.
ar=np.array([[[ 1.,4., 0.],
[ 3., 1., 2.],[ 3., 1., 2.]],[[ 1.,4., 0.],
[ 3., 1., 2.],[ 3., 1., 2.]]])
print(np.ndim(ar))


In [ ]:
import numpy as np
ar=np.array([[ 1., 0., 0.],
       [ 0., 1., True]])
print(ar[1][2].dtype)
print(ar)

In [ ]:
import numpy as np
ar=np.array([[ 1., 0., 0.],#3 columns x2 rows
       [ 0., 1., 2.]])
print(np.size(ar))


In [ ]:
a = np.array( [20,30,40,50] )#elementwise
b = np.arange( 4 )
c=a-b

In [ ]:
b

In [ ]:
c

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c=a+b
d=a**2

In [ ]:
c

In [ ]:
d

In [ ]:
A = np.array( [[1,1],
[0,1]] )
B = np.array( [[2,0],
[3,4]] )
C=A*B
print(C)


In [ ]:
#indexing slicing
a = np.arange(10)**3
print(a)



In [ ]:
a[2]


In [ ]:
a[2:5]

In [ ]:
array1 = np.arange(12).reshape(4,3)#2d array
print(array1)


In [ ]:
array1[3][1]

In [ ]:
array1 = np.arange(16).reshape(4,4)#array slicing
print(array1)


In [ ]:
array1[0:2,1:3]

In [ ]:
np.ndim(array1)

In [ ]:
np.ndim(array1[0:2,1:3])

In [ ]:
np.ndim(array1[0])

In [ ]:
A = np.array( [[1,1],
    [0,1]] )
B = np.array( [[2,0],
    [3,4]] )
C=A*B
print(C)


In [ ]:
C[1][1]

In [ ]:
a = np.arange(10)**3
a

In [ ]:
a[3]

In [ ]:
array1 = np.arange(16).reshape(4,4)

In [ ]:
array1

In [ ]:
array1[0:2, 1:3]

In [5]:
#Create a 1-D array from 0 to 50
array1 = np.arange(51)
print("Array from 0 to 50:")
print(array1)

Array from 0 to 50:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [7]:
#Create a 1-D array from 10 to 50
array2 = np.arange(10, 51)
print("\nArray from 10 to 50:")
print(array2)


Array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
import numpy as np

# Create a 1-D array from 0 to 50
array1 = np.arange(51)
print("Array from 0 to 50:")
print(array1)

# Create a 1-D array from 10 to 50
array2 = np.arange(10, 51)
print("\nArray from 10 to 50:")
print(array2)