<a href="https://colab.research.google.com/github/cjayjonathan/285-Machine-Learning-Projects-with-Python/blob/main/Week_2_Practicals_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1) Create a 1-D array going from 0 to 50 and an array from 10 to 50.
array_0_50 = np.arange(51)
array_10_50 = np.arange(10, 51)
print("1-D array from 0 to 50:", array_0_50)
print("1-D array from 10 to 50:", array_10_50)

1-D array from 0 to 50: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
1-D array from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [2]:
# 2) Create a 1-D numpy array.
one_d_array = np.array([1, 2, 3, 4, 5])
print("\nCreated 1-D array:", one_d_array)


Created 1-D array: [1 2 3 4 5]


In [3]:
# 3) Create a 2-D numpy array.
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nCreated 2-D array:\n", two_d_array)


Created 2-D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 4) Create two 2-D numpy arrays and do (+,-,/,*) operations on them.
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])
print("\nArray A:\n", array_a)
print("Array B:\n", array_b)
print("Addition (A + B):\n", array_a + array_b)
print("Subtraction (A - B):\n", array_a - array_b)
print("Multiplication (A * B):\n", array_a * array_b)
print("Division (A / B):\n", array_a / array_b)


Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Addition (A + B):
 [[ 6  8]
 [10 12]]
Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]
Multiplication (A * B):
 [[ 5 12]
 [21 32]]
Division (A / B):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [5]:
# 5) Show an example of index operations on a 2-D array?
print("\nElement at index [1, 0] in 2-D array:", two_d_array[1, 0])


Element at index [1, 0] in 2-D array: 4


In [6]:
# 6) Show an example of slicing operation on a 2-D array?
print("\nSlice of 2-D array (first two rows, all columns):\n", two_d_array[:2, :])
print("Slice of 2-D array (all rows, last two columns):\n", two_d_array[:, 1:])


Slice of 2-D array (first two rows, all columns):
 [[1 2 3]
 [4 5 6]]
Slice of 2-D array (all rows, last two columns):
 [[2 3]
 [5 6]
 [8 9]]


In [7]:
# 7) Show an example of slicing operations on 1-D array?
print("\nSlice of 1-D array (elements from index 2 to 4):", one_d_array[2:5])


Slice of 1-D array (elements from index 2 to 4): [3 4 5]


In [8]:
# 8) Show an example of index operations on a 1-D array?
print("\nElement at index 3 in 1-D array:", one_d_array[3])


Element at index 3 in 1-D array: 4


In [9]:
# 9) Create a random empty 2-D array and only ones 2-D array then show mathematical operations on them.
random_empty_array = np.empty((2, 2)) # Note: np.empty creates an array with arbitrary values
ones_array = np.ones((2, 2))
print("\nRandom (empty) 2-D array:\n", random_empty_array)
print("Ones 2-D array:\n", ones_array)
print("Addition (random_empty_array + ones_array):\n", random_empty_array + ones_array)
print("Multiplication (random_empty_array * ones_array):\n", random_empty_array * ones_array)


Random (empty) 2-D array:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Ones 2-D array:
 [[1. 1.]
 [1. 1.]]
Addition (random_empty_array + ones_array):
 [[1.2        1.33333333]
 [1.42857143 1.5       ]]
Multiplication (random_empty_array * ones_array):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
